### ISSUE TITLE
Enforcer 5.3: DaemonSet fails to create Pods with multi_cluster set to false

### ISSUE THREAD

**Issue by brendonthiede** [aquasecurity/aqua-helm#204]
If `multi_cluster` is set to `false` (the default), the ServiceAccount is not created, but the DaemonSet doesn't check for the `multi_cluster` value and always sets `spec.template.spec.serviceAccount` to `{{ .Release.Namespace }}-sa`, which when the ServiceAccount does not exist/`multi_cluster` is `false`, the Pods can't be created and you see the following event:

```
Events:
  Type     Reason        Age                  From                  Message
  ----     ------        ----                 ----                  -------
  Warning  FailedCreate  47s (x15 over 2m9s)  daemonset-controller  Error creating: pods "enforcer-ds-" is forbidden: error looking up service account aqua/aqua-sa: serviceaccount "aqua-sa" not found
```

My current work around is to set `multi_cluster: true` and let the ServiceAccount get created.

**Comment by brendonthiede** [comment]
Looking at the enforcer template in the 5.0 branch, the ServiceAccount is always created. At first I thought that the `serviceAccount` in the spec should be conditional, but I'm not sure why the `multi_cluster` value was added. From a quick test, wrapping the `serviceAccount` in the spec with an `if` appears to work (`enforcer/templates/enforcer-daemonset.yaml`):

```yaml
    {{- if .Values.multi_cluster }}
      serviceAccount: {{ .Release.Namespace }}-sa
    {{- end }}
```

**Comment by brendonthiede** [comment]
I have tried proposing a change, with the assumption that the DaemonSet should not reference the ServiceAccount when it does not exist: https://github.com/aquasecurity/aqua-helm/pull/205

**Comment by KoppulaRajender** [comment]
Hi @brendonthiede, The purpose of having a multi_cluster variable is to mention whether the enforcer is going to deploy on the same cluster where the server/gateway deployed or a different one. Because if it is the same cluster we use the same sa created by server components.

In case you're deploying enforcer agent in a different cluster then you have to enable the multi_cluster to true.

in 5.0 the service account created with {{ .Release.Name }} and not with {{ .Release.Namespace }}. so here in 5.3 if we deploy enforcer and server components on the same cluster will encounter conflict in having the same sa names for 2 deployments.

let us know if you still have any issue with the deployment.
