### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by mangesj** [aquasecurity/aqua-helm#67]
We've currently got Aqua Helm chart running console and a scanner, but when scanning a particular image locally from my Mac command line, we're getting the error 

"twirp error unknown: Error from intermediary with HTTP status code 413 "Request Entity Too Large""
The image is 1.4gb. 
The confusing factor in this, is that when scanning the same image from the console, it works fine.

**Comment by StefanMadsen** [comment]
I had a similar issue, - this was due to a ingress controller not allowing "large" payloads.

Our nginx ingress controller reads annotations and could be set via our helm install with set commands:
        --set web.ingress.annotations."nginx\.ingress\.kubernetes\.io/client-body-buffer-size"="<size you need>" \
        --set web.ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-body-size"="<size you need>" \

it most likely depends on your loadbalancer/ingress

more here:
https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md

and heres more info : 
https://github.com/kubernetes/ingress-nginx/issues/1824
