### ISSUE TITLE
starboard.resources variable is absent in Configuration Variables list

### ISSUE THREAD

**Issue by praveensirvi-aqua** [aquasecurity/aqua-helm#782]
**starboard.resources** variable is used in **starboard-deployment.yaml** file but starboard.resources variable is absent in **Configuration Variables** list. Kindly update the Configuration Variables list.

**Comment by adishaull** [comment]
Hi @praveensirvi-aqua , please see the values.yaml https://github.com/aquasecurity/aqua-helm/blob/9510077c9767637516b6998e64688bd3e034b1b2/kube-enforcer/values.yaml#L334

**Comment by semyonmor** [comment]
@praveensirvi-aqua 
Can you pls explain what the problem is with the starboard resource configuration?
 We have the default values defined on the deployment manifest https://github.com/aquasecurity/aqua-helm/blob/9510077c9767637516b6998e64688bd3e034b1b2/kube-enforcer/templates/starboard-deployment.yaml#L72
 and it could be changed from values.yaml
 https://github.com/aquasecurity/aqua-helm/blob/9510077c9767637516b6998e64688bd3e034b1b2/kube-enforcer/values.yaml#L334

**Comment by praveensirvi-aqua** [comment]
@adishaull @semyonmor   **starboard.resources** variable is used in **starboard-deployment.yaml** file but starboard.resources variable is absent in Configuration Variables list like starboard.nodeselector .

https://github.com/aquasecurity/aqua-helm/tree/9510077c9767637516b6998e64688bd3e034b1b2/kube-enforcer#configurable-variables
