### ISSUE TITLE
Kube Enforcer's starboard operator to trivy operator migration

### ISSUE THREAD

**Issue by tnycum** [aquasecurity/aqua-helm#791]
I'm confused what is happening with the Starboard to Trivy migration. Should I be trying to deploy the latest version of the kube-enforcer charts at the moment?

I have these concerns:

1. Why does [values.yaml](https://github.com/aquasecurity/aqua-helm/blob/2022.4/kube-enforcer/values.yaml#L284) use such an old version of the trivy operator (from Feb 2023 instead of Sep 2023)? Would the latest trivy operator version work properly?
2. Is there any documentation anywhere for performing this migration? It seems like the [README](https://github.com/aquasecurity/aqua-helm/blob/2022.4/kube-enforcer/README.md) still only discusses Starboard and same thing for [Aqua's docs for deploying Kube Enforcer](https://docs.aquasec.com/v2022.4/platform/deploy-aqua-enterprise/deploy-on-kubernetes-and-openshift/deploy-k8s-aqua-kubeenforcers/).
3. Are there any version compatibility issues to be aware of with what version of Aqua Kube Enforcer needs to be deployed with trivy versus starboard? e.g. Trivy wouldn't work with older versions of Kube Enforcer, etc.

**Comment by deven0t** [comment]
Hi @tnycum 
Sorry for the delay in the response. Here are my responses to your queries
1. Ideally latest Trivy-operator should work fine, but as trivy-operator is adding new feature regularly, so there might be few settings we will enable/disable to make it work properly. So we internally perform QA before updating to latest version. Currently it is updated to `0.16.1` version.
2. We captured documentation around trivy-operator, as we were not done with Sizing guide, we brought back starboard as default option. From migration point of view, removing KubeEnforcer+starboard and installing with KubeEnforcer+trivyOperator should take care of migration. We shouldnt have change in our findings from cluster except underline change in the engine(ie. instead of starboard, we will see trivy-operator)
3. Yes there is version compatibility required for Trivy-operator to work. Update 24 or higher version of KubeEnforcer is required to work with trivy-operator. Lower will not work properly. New KubeEnforcer version(u24 and later) is capable to work with Trivy-operator and starboard, So either of them can be deployed with KubeEnforcer.

Thank you for raising these queries, we will capture them once we make Trivy-operator as default option.

Regards,
Devendra
