### ISSUE TITLE
Breaking changes with active:active commit and chart version unchanged

### ISSUE THREAD

**Issue by cdunford** [aquasecurity/aqua-helm#82]
There was an update made to the server chart (specifically https://github.com/aquasecurity/aqua-helm/commit/ce60ce8e7fdaf83413a226846da242d7679756b5#diff-cf1e8c14e54505f60aa10ceb8d5d8ab3) that removed values that we were setting (specifically the audit DB parameters `auditHost`, `auditUser` and `auditPassword`). Now our console container will no longer start as it cannot connect to the audit DB and one of our environments is unusable.

The bigger problem here is that the chart version did not change whatsoever with this change, and was published to `helm.aquasec.com` replacing the previous revision of 4.6.0. We have no way to reference the previous, working version of the chart, as it appears it is completely replaced by this new version.

Whenever changes are made to the chart, at the very least the chart patch version should be changed (and possibly major/minor version depending on the scope/nature of the change) to avoid impacting anyone who has pinned to a specific version of the chart. Once a specific version of the chart is published, it should not be modified.

**Comment by agilgur5** [comment]
Saw https://github.com/aquasecurity/aqua-helm/commit/70ae91735fff3db823569c6a5bab689267e3ba9a which also makes a large amount of breaking changes...

I'm not sure if the Chart registry was updated with those changes, but these kinds of drastic breaking changes without upgrading major and without so much as a changelog (not to mention these commits and PRs basically just say "updates"), pretty much make this repo unusable due to poor maintenance and lack of care...

**Comment by cdunford** [comment]
@agilgur5 - I'm now using the helm git plugin to consume these charts direct from the github repo and I pin to a specific commit. Seems to be the only safe thing to do.

**Comment by agilgur5** [comment]
Yea but without a changelog and without SemVer updates are basically ???

**Comment by xB-2048** [comment]
@cdunford Thanks for reporting the issue.

We will manage the chart version and changelog going forward.
